{% set name = "mne-bids" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c653ff12d4954103d6178e300e3c828a638312f8099081c8668792510a279923

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mne_bids = mne_bids.commands.run:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools
    - mne-base >=0.24
    - numpy >=1.16.0
    - scipy >=1.5.0
    - nibabel >=2.5
    - pybv >=0.6
    - edflib-python >=1.0.2
    - pandas >=0.24.0
    - matplotlib-base >=3.1

test:
  imports:
    - mne_bids
  commands:
     # Test the entry point.
    - mne_bids --version

about:
  home: https://mne.tools/mne-bids/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An MNE project for organizing and formatting MEG and EEG data according to the BIDS specification
  dev_url: https://github.com/mne-tools/mne-bids

extra:
  recipe-maintainers:
    - hoechenberger
    - jasmainak
    - sappelhoff
