{% set name = "mne-bids" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e117f7646b547504d91dd3f5faa34eba82f01a6ad5634fc04a79a566cb099dce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mne_bids = mne_bids.commands.run:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - nibabel
    - mne >=0.21
    - pybv >=0.2

test:
  imports:
    - mne_bids
  commands:
     # Test the entry point.
    - mne_bids --version

about:
  home: https://mne.tools/mne-bids/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An MNE project for organizing and formatting MEG and EEG data according to the BIDS specification
  dev_url: https://github.com/mne-tools/mne-bids

extra:
  recipe-maintainers:
    - hoechenberger
    - jasmainak
