{% set name = "mne-bids" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8a3ac7fb586ba2be70eb687c67ae060b42693078c56232180b27161124c22f72

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mne_bids = mne_bids.commands.run:main

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - mne-base >=1.5
    - numpy >=1.21.2
    - scipy >=1.7.1
    - nibabel >=3.2.1
    - pybv >=0.7.5
    - eeglabio >=0.0.2
    - pymatreader >=0.0.30
    - matplotlib-base >=3.5
    - pandas >=1.3.2
    - edflib-python >=1.0.6
    - edfio >=0.2.1
    - defusedxml

test:
  imports:
    - mne_bids
  commands:
     # Test the entry point.
    - mne_bids --version

about:
  home: https://mne.tools/mne-bids/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An MNE project for organizing and formatting MEG and EEG data according to the BIDS specification
  dev_url: https://github.com/mne-tools/mne-bids

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
    - jasmainak
    - sappelhoff
