{% set name = "mne-bids" %}
{% set version = "0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d4ee9a39dc1d96fbbad18d3e411c8170ddd32bf4071f325951dc5df616e5c06

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mne_bids = mne_bids.commands.run:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - setuptools >=46.4.0
    - mne-base >=1.2
    - numpy >=1.18.1
    - scipy >=1.5.0
    - nibabel >=2.5
    - pybv >=0.7.5
    - pymatreader >=0.0.30
    - edflib-python >=1.0.6
    - pandas >=1.0.0
    - matplotlib-base >=3.1

test:
  imports:
    - mne_bids
  commands:
     # Test the entry point.
    - mne_bids --version

about:
  home: https://mne.tools/mne-bids/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An MNE project for organizing and formatting MEG and EEG data according to the BIDS specification
  dev_url: https://github.com/mne-tools/mne-bids

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
    - jasmainak
    - sappelhoff
