{% set name = "mne-bids" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28f36e10f08452795e4709bcec749bed95f06666fc983126cfbf8e82108301bf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mne_bids = mne_bids.commands.run:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools >=46.4.0
    - mne-base >=1.0
    - numpy >=1.16.0
    - scipy >=1.5.0
    - nibabel >=2.5
    - pybv >=0.7.3
    - pymatreader >=0.0.29
    - edflib-python >=1.0.6
    - pandas >=0.24.0
    - matplotlib-base >=3.1
    - jinja2

test:
  imports:
    - mne_bids
  commands:
     # Test the entry point.
    - mne_bids --version

about:
  home: https://mne.tools/mne-bids/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An MNE project for organizing and formatting MEG and EEG data according to the BIDS specification
  dev_url: https://github.com/mne-tools/mne-bids

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
    - jasmainak
    - sappelhoff
