{% set name = "mne-bids" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d72260731bdee164f3b0cb2475ad7db0bc87fa7ccfdd250b11518c01d8567170

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mne_bids = mne_bids.commands.run:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.15.4
    - scipy >=1.5.0
    - nibabel >=2.2
    - mne >=0.21.2
    - pybv >=0.5
    - pandas >=0.23.4
    - matplotlib-base

test:
  imports:
    - mne_bids
  commands:
     # Test the entry point.
    - mne_bids --version

about:
  home: https://mne.tools/mne-bids/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An MNE project for organizing and formatting MEG and EEG data according to the BIDS specification
  dev_url: https://github.com/mne-tools/mne-bids

extra:
  recipe-maintainers:
    - hoechenberger
    - jasmainak
    - sappelhoff
